### ISSUE TITLE
[Graphic design task] Design a GitHub preview image

### ISSUE THREAD

**Issue by yochannah** [intermine/design-materials#55]
The InterMine repos in general need to have social preview images. 

## Task: 

Create a social preview image based on the specs shown here: https://help.github.com/en/articles/customizing-your-repositorys-social-media-preview - you can use your creativity to make something that you think looks nice.

Resources you can use include InterMine logos from the logos/intermine folder of this repo (but don't use items from other folders; much of this repo is very old and not in use), as well as any images or text from intermine.org.

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.
3. Bask in glory

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by azhsetiawan** [comment]
Hi @yochannah 
I wanna take this

**Comment by yochannah** [comment]
@azhsetiawan awesome - go ahead! 👍
